#!/usr/bin/python3
import cgi
import cgitb; cgitb.enable()
import sqlite3

# DB Connection
conn = sqlite3.connect("tkhelp.db")
db = conn.cursor()

# Basic CGI Operations
form = cgi.FieldStorage()
print("Content-Type: text/html")
print()
search_query = form.getvalue("q")
mode = form.getvalue("mode")

# Basic HTML Construct
print("<html>")
print("<head><title>tkhelp at Web</title>")
print("<link rel='stylesheet' type='text/css' href='../css/tkhelp.css' />")
print("</head><body><div id='container'>")

if search_query != None:
	print("<div id='metatop'><h1>Suchergebnis f&uuml;r '%(query)s'</h1></div>" % { "query" : search_query })
	
	if search_query.rfind("+"):
		# For multiple search
		querys = search_query.split("+")
		for query in querys:
			result = db.execute("SELECT * FROM webdocu WHERE name = '%(query)s'" % { "query" : query })
			for row in result:
				print("<a href='getcontent.py?page=%(site)s'>%(site)s</a><br /><i>%(keywords)s</i><br /><br />" % { "site" : row[0], "keywords" : row[1] })
				
		
	else:
		result = db.execute("SELECT * FROM webdocu WHERE name = '%(query)s'" % { "query" : search_query })
		for row in result:
			print("<a href='getcontent.py?page=%(site)s'>%(site)s</a><br /><i>%(keywords)s</i><br /><br />" % { "site" : row[0], "keywords" : row[1] })

elif mode == "index":
	print("<div id='metatop'><h1>Indexseite</h1></div><div id='content'><h2><a href='../index.html' title='Zurueck zur Startseite'>Zur&uuml;ck zur Startseite</a></h2>")
	result = db.execute("SELECT * FROM webdocu")
	for row in result:
		print("<a href='getcontent.py?page=%(site)s'>%(site)s</a><br />" % { "site" : row[0] })
	
	print("</div>");
	
# End of Document
print("</div> <!-- End of Container -->")
print("</body>")
print("</html>")
print("<!-- This Contents generated by tkhelp Webinterface -->")
